# Generated by Django 5.2.1 on 2025-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('QUEEN', 'Queen Size'), ('KING', 'King Size')], default='SINGLE', max_length=10),
        ),
    ]
