# Generated by Django 5.2 on 2025-04-21 06:26

import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    Hotel = apps.get_model('bookings', 'Hotel')
    Booking = apps.get_model('bookings', 'Booking')

    hotel = Hotel.objects.create(
        name="Default Hotel",
        location="Global",
        is_active=True
    )
    
    # Update all bookings
    Booking.objects.update(hotel=hotel)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room_review_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(upload_to='hotels/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookings.hotel'),
            preserve_default=False,
        ),
    ]
