# Generated by Django 5.2.1 on 2025-05-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_uid_alter_hotel_uid_alter_review_uid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
