# Generated by Django 5.2.1 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status_alter_room_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default=list, help_text='Up to 5 amenities in a list'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-star'), (2, '2-star'), (3, '3-star'), (4, '4-star'), (5, '5-star')], default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
