# Generated by Django 5.2.1 on 2025-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_room_room_type_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default=list, help_text='Up to 5 amenities'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
